### ISSUE TITLE
Support for s390x and ppc64le

### ISSUE THREAD

**Issue by Jinnkunn** [AISViz/AISdb#19]
Currently, AISdb is not being developed for the s390x and ppc64le architectures. This is due to a dependency chain where version 0.16.20 of 'ring' is required by 'rustls', which in turn is needed by 'tungstenite' for the receiver component. The latest 'ring' release, version 0.17.0, is expected to provide support for both s390x and ppc64le. We plan to address this compatibility issue promptly following the release of the updated dependencies.

issue related to ring: 
* https://github.com/briansmith/ring/issues/986
* https://github.com/temporalio/sdk-python/issues/394

The most recent version of [rustls](https://github.com/rustls/rustls) (0.21.8) now incorporates ring 0.17.0 as per its GitHub repository. However, there is a version mismatch since tungstenite-rs employs rustls 0.21.0, which depends on the outdated ring 0.16.20. This versioning conflict is the root cause for the current lack of support for s390x and ppc64le architectures in AISdb. The issue will be remedied once tungstenite-rs updates to a rustls version that utilizes ring 0.17.0.

**Comment by gabrielspadon** [comment]
This is not the only build affected; aarch64 is also broken. Because of this and due to the high-risk threat in #46, I removed support to all archs but x86 and x86_64. This means that we will be on all Windows/Linux desktop and server systems but not on Apple M1/M2 laptops. This can be revisited when ring, the broken dependency for the security check, gets updated.
